#!/usr/bin/env bash

## Usage: geno <reference.fasta> <input.bam>
## Requirement: bcftools v1.0 or later must be in your $PATH
## Final files will be written to the directory from which the script is initiated

BASEDIR=$(dirname $0)
REFERENCE=$1
BAM=$2
NAME=`echo $BAM|awk -F'/' '{print $NF}'|awk -F'.bam' '{print $1}'`

# Genotype the 387 test positions across the genome, filter to calls with DP >= 5
bcftools mpileup \
    --no-BAQ \
    --max-depth 5000 \
    --min-MQ 0 \
    --min-BQ 13 \
    --fasta-ref ${REFERENCE} \
    --regions-file ${BASEDIR}/positions_387_hg19.txt \
    ${BAM} \
    | \
    bcftools call \
    --threads 4 \
    --consensus-caller \
    | \
    bcftools sort \
    --output-type v \
    --output-file ${NAME}.snpsniffer.vcf

