#!/usr/bin/env bash

## Usage: geno <reference.fasta> <input.bam>
## Requirement: bcftools v1.0 or later must be in your $PATH
## Final files will be written to the directory from which the script is initiated

BASEDIR=$(dirname $0)
REFERENCE=$1
BAM=$2
NAME=`echo $BAM|awk -F'/' '{print $NF}'|awk -F'.bam' '{print $1}'`

# Genotype the 387 test positions across the genome, filter to calls with DP >= 5
bcftools mpileup \
    --no-BAQ \
    --max-depth 5000 \
    --min-MQ 0 \
    --min-BQ 13 \
    --fasta-ref ${REFERENCE} \
    --regions-file ${BASEDIR}/positions_387_hg38_ucsc.txt \
    ${BAM} \
    | \
    bcftools call \
    --threads 4 \
    --consensus-caller \
    | \
    bcftools sort \
    --output-type v \
    --output-file temp.snpsniffer.sorted.vcf

# The database file cannot contain chr1, I suspect the java app expects a single character string
# So the output vcf needs to be edited to remove the chr from the contig names

# Extract the header
grep "#" temp.snpsniffer.sorted.vcf > temp.snpsniffer.header
grep -v "#" temp.snpsniffer.sorted.vcf | sed 's/chr//g' > temp.snpsniffer.calls
cat temp.snpsniffer.header temp.snpsniffer.calls > ${NAME}.snpsniffer.vcf

# Cleanup directory
rm temp.snpsniffer.*